#!/bin/bash
#
# Usage:
#   gtf_create_relion_it_options.sh [-p ANGPIX] [-e DOSE_PER_FRAME] [-u DEFOCUS_MAX] [-l DEFOCUS_MIN] [-s DO_PHASESHIFT] [-d]
#   
# Arguments & Options:
#   -d                 : Run with GoToFly(JK) debug mode
#   
#   -h                 : Help option displays usage
#   
# Example:
#   $ gtf_create_relion_it_options.sh -d
#   
# Debug Script:
#   gtf_rsync_detector_server_debug.sh
# 
<< DEBUG_NOTES
[*] List of template variables
XXX_GTF_ANGPIX_XXX=0.88
XXX_GTF_DOSE_PER_FRAME_XXX=1.00
XXX_GTF_CTFFIND_DEFOCUS_MAX_XXX=30000
XXX_GTF_CTFFIND_DEFOCUS_MIN_XXX=5000
XXX_GTF_CTFFIND_DO_PHASESHIFT_XXX=False

[*] List of template constants for KEK Cryo-EM facility
XXX_GTF_VOLTAGE_XXX=200.0
XXX_GTF_CS_XXX=2.7
XXX_GTF_IMPORT_IMAGES_XXX='Micrographs/\*.mrc'

XXX_GTF_MOTIONCOR_DO_OWN_XXX=True
XXX_GTF_MOTIONCOR_THREADS_XXX=4
XXX_GTF_MOTIONCOR_EXE_XXX='/gpfs/data/EM/software/MotionCor2/MotionCor2_1.4.0_Cuda101'
XXX_GTF_MOTIONCOR_GPU_XXX='0'
XXX_GTF_MOTIONCOR_MPI_XXX=1
XXX_GTF_MOTIONCOR_MOTIONCOR_PATCHES_X_XXX=5
XXX_GTF_MOTIONCOR_MOTIONCOR_PATCHES_Y_XXX=5
XXX_GTF_MOTIONCOR_BFACTOR_XXX=200
XXX_GTF_MOTIONCOR_BINNING_XXX=1
XXX_GTF_MOTIONCOR_DEFECTFILE_XXX=''
XXX_GTF_MOTIONCOR_GAINFLIP_XXX='No flipping (0)'
XXX_GTF_MOTIONCOR_GAINROT_XXX='No rotation (0)'

XXX_GTF_AMPL_CONTRAST_XXX=0.1
XXX_GTF_CTFFIND_BOXSIZE_XXX=512
XXX_GTF_CTFFIND_ASTIGMATISM_XXX=100
XXX_GTF_CTFFIND_MAXRES_XXX=4
XXX_GTF_CTFFIND_MINRES_XXX=30
XXX_GTF_CTFFIND_DEFOCUS_STEP_XXX=100
XXX_GTF_CTFFIND_DO_IGNORE_SEARCH_PARAMS_XXX=False
XXX_GTF_CTFFIND_DO_EPA_XXX=True
XXX_GTF_GCTF_EXE_XXX='/gpfs/data/EM/software/GCTF_Gautomatch_Cu10.1/GCTF_v1.18_sm30-75_cu10.1'
XXX_GTF_GCTF_GPU_XXX='1'
XXX_GTF_USE_CTFFIND_INSTEAD_XXX=False
XXX_GTF_CTFFIND4_EXE_XXX='/gpfs/data/EM/software/ctffind-4.1.14/ctffind'
XXX_GTF_CTFFIND_MPI_XXX=1

DEBUG_NOTES
# 

usage_exit() {
        echo "GoToFly(JK): Usage $0 [-p ANGPIX] [-e DOSE_PER_FRAME] [-u DEFOCUS_MAX] [-l DEFOCUS_MIN] [-s DO_PHASESHIFT] [-d]  " 1>&2
        echo "GoToFly(JK): Exiting(1)..."
        exit 1
}

# Check if the number of command line arguments is valid
if [[ $# -gt 11 && $# -ne 1 ]]; then
    echo "GoToFly(JK): Invalid number of arguments ($#)"
    usage_exit
fi

# Initialize variables with default values
GTF_ANGPIX=0.88
GTF_DOSE_PER_FRAME=1.00
GTF_CTFFIND_DEFOCUS_MAX=30000
GTF_CTFFIND_DEFOCUS_MIN=5000
GTF_CTFFIND_DO_PHASESHIFT='False'
GTF_DEBUG_MODE=0   # 0 (off) by default

# Parse command line arguments
while getopts p:e:u:l:s:dh OPT
do
    case "$OPT" in
        p)  GTF_ANGPIX=$OPTARG
            echo "GoToFly(JK): GoToFly(JK) Pixel size [A] is specified"
            ;;
        e)  GTF_DOSE_PER_FRAME=$OPTARG
            echo "GoToFly(JK): GoToFly(JK) Dose per frame [e/A^2/frame] is specified"
            ;;
        u)  GTF_CTFFIND_DEFOCUS_MAX=$OPTARG
            echo "GoToFly(JK): GoToFly(JK) Maximum defocus [A] is specified"
            ;;
        l)  GTF_CTFFIND_DEFOCUS_MIN=$OPTARG
            echo "GoToFly(JK): GoToFly(JK) Minimum defocus [A] is specified"
            ;;
        s)  GTF_CTFFIND_DO_PHASESHIFT=$OPTARG
            echo "GoToFly(JK): GoToFly(JK) Do phase shift is specified"
            ;;
        d)  GTF_DEBUG_MODE=1
            echo "GoToFly(JK): GoToFly(JK) debug mode is specified"
            ;;
        h)  usage_exit
            ;;
        \?) echo "GoToFly(JK): [gtf_ERROR] Invalid option $OPTARG is specified!"
            usage_exit
            ;;
    esac
done

echo "GoToFly(JK): Running with following parameters..."
echo "GoToFly(JK):   Pixel size in Angstrom       : ${GTF_ANGPIX}"
echo "GoToFly(JK):   Dose per frame [e/A^2/frame] : ${GTF_DOSE_PER_FRAME}"
echo "GoToFly(JK):   Maximum defocus [A]          : ${GTF_CTFFIND_DEFOCUS_MAX}"
echo "GoToFly(JK):   Minimum defocus [A]          : ${GTF_CTFFIND_DEFOCUS_MIN}"
echo "GoToFly(JK):   Do phase shift               : ${GTF_CTFFIND_DO_PHASESHIFT}"
echo "GoToFly(JK):   Debug Mode                   : ${GTF_DEBUG_MODE}"

if [[ ${GTF_DEBUG_MODE} != 0 ]]; then echo "GoToFly(JK): [GTF_DEBUG] --------------------------------------------------"; fi
if [[ ${GTF_DEBUG_MODE} != 0 ]]; then echo "GoToFly(JK): [GTF_DEBUG] Hello gtf_create_relion_it_options.sh"; fi
if [[ ${GTF_DEBUG_MODE} != 0 ]]; then echo "GoToFly(JK): [GTF_DEBUG] --------------------------------------------------"; fi

# Set template constants for KEK Cryo-EM facility
GTF_VOLTAGE=200.0
GTF_CS=2.7
GTF_IMPORT_IMAGES='Micrographs/\*.mrc'

GTF_MOTIONCOR_DO_OWN=True
GTF_MOTIONCOR_THREADS=4
GTF_MOTIONCOR_EXE='/gpfs/data/EM/software/MotionCor2/MotionCor2_1.4.0_Cuda101'
GTF_MOTIONCOR_GPU='0'
GTF_MOTIONCOR_MPI=1
GTF_MOTIONCOR_MOTIONCOR_PATCHES_X=5
GTF_MOTIONCOR_MOTIONCOR_PATCHES_Y=5
GTF_MOTIONCOR_BFACTOR=200
GTF_MOTIONCOR_BINNING=1
GTF_MOTIONCOR_DEFECTFILE=''
GTF_MOTIONCOR_GAINFLIP='No flipping (0)'
GTF_MOTIONCOR_GAINROT='No rotation (0)'

GTF_AMPL_CONTRAST=0.1
GTF_CTFFIND_BOXSIZE=512
GTF_CTFFIND_ASTIGMATISM=100
GTF_CTFFIND_MAXRES=4
GTF_CTFFIND_MINRES=30
GTF_CTFFIND_DEFOCUS_STEP=100
GTF_CTFFIND_DO_IGNORE_SEARCH_PARAMS=False
GTF_CTFFIND_DO_EPA=True
GTF_GCTF_EXE='/gpfs/data/EM/software/GCTF_Gautomatch_Cu10.1/GCTF_v1.18_sm30-75_cu10.1'
GTF_GCTF_GPU='1'
GTF_USE_CTFFIND_INSTEAD=False
GTF_CTFFIND4_EXE='/gpfs/data/EM/software/ctffind-4.1.14/ctffind'
GTF_CTFFIND_MPI=1

# Set constants for this script
### GTF_SH_DIR_PATH='/gpfs/data/EM/ikeda-em/mrk_rsync_test'
GTF_RELION_IT_OPTIONS_TEMPLATE_FILE_NAME='gtf_relion_it_options_template.py'
GTF_RELION_IT_OPTIONS_FILE_NAME='relion_it_options.py'

echo "GoToFly(JK): Creating relion_it_options.sh from template..."
### cp ${GTF_SH_DIR_PATH}/${GTF_RELION_IT_OPTIONS_TEMPLATE_FILE_NAME} ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
cp ./${GTF_RELION_IT_OPTIONS_TEMPLATE_FILE_NAME} ./${GTF_RELION_IT_OPTIONS_FILE_NAME}

# Replace variable strings in template to actual values

# [*] Template variables
# XXX_GTF_ANGPIX_XXX -> ${GTF_ANGPIX}
sed -i "s@XXX_GTF_ANGPIX_XXX@${GTF_ANGPIX}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_DOSE_PER_FRAME_XXX -> ${GTF_DOSE_PER_FRAME}
sed -i "s@XXX_GTF_DOSE_PER_FRAME_XXX@${GTF_DOSE_PER_FRAME}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_DEFOCUS_MAX_XXX -> ${GTF_CTFFIND_DEFOCUS_MAX}
sed -i "s@XXX_GTF_CTFFIND_DEFOCUS_MAX_XXX@${GTF_CTFFIND_DEFOCUS_MAX}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_DEFOCUS_MIN_XXX -> ${GTF_CTFFIND_DEFOCUS_MIN}
sed -i "s@XXX_GTF_CTFFIND_DEFOCUS_MIN_XXX@${GTF_CTFFIND_DEFOCUS_MIN}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_DO_PHASESHIFT_XXX -> ${GTF_CTFFIND_DO_PHASESHIFT}
sed -i "s@XXX_GTF_CTFFIND_DO_PHASESHIFT_XXX@${GTF_CTFFIND_DO_PHASESHIFT}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}

# [*] Template constants for KEK Cryo-EM facility
# XXX_GTF_VOLTAGE_XXX -> ${GTF_VOLTAGE}
sed -i "s@XXX_GTF_VOLTAGE_XXX@${GTF_VOLTAGE}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CS_XXX -> ${GTF_CS}
sed -i "s@XXX_GTF_CS_XXX@${GTF_CS}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_IMPORT_IMAGES_XXX -> ${GTF_IMPORT_IMAGES}
sed -i "s@XXX_GTF_IMPORT_IMAGES_XXX@${GTF_IMPORT_IMAGES}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}

# XXX_GTF_MOTIONCOR_DO_OWN_XXX -> ${GTF_MOTIONCOR_DO_OWN}
sed -i "s@XXX_GTF_MOTIONCOR_DO_OWN_XXX@${GTF_MOTIONCOR_DO_OWN}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_THREADS_XXX -> ${GTF_MOTIONCOR_THREADS}
sed -i "s@XXX_GTF_MOTIONCOR_THREADS_XXX@${GTF_MOTIONCOR_THREADS}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_EXE_XXX -> ${GTF_MOTIONCOR_EXE}
sed -i "s@XXX_GTF_MOTIONCOR_EXE_XXX@${GTF_MOTIONCOR_EXE}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_GPU_XXX -> ${GTF_MOTIONCOR_GPU}
sed -i "s@XXX_GTF_MOTIONCOR_GPU_XXX@${GTF_MOTIONCOR_GPU}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_MPI_XXX -> ${GTF_MOTIONCOR_MPI}
sed -i "s@XXX_GTF_MOTIONCOR_MPI_XXX@${GTF_MOTIONCOR_MPI}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_MOTIONCOR_PATCHES_X_XXX -> ${GTF_MOTIONCOR_MOTIONCOR_PATCHES_X}
sed -i "s@XXX_GTF_MOTIONCOR_MOTIONCOR_PATCHES_X_XXX@${GTF_MOTIONCOR_MOTIONCOR_PATCHES_X}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_MOTIONCOR_PATCHES_Y_XXX -> ${GTF_MOTIONCOR_MOTIONCOR_PATCHES_Y}
sed -i "s@XXX_GTF_MOTIONCOR_MOTIONCOR_PATCHES_Y_XXX@${GTF_MOTIONCOR_MOTIONCOR_PATCHES_Y}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_BFACTOR_XXX -> ${GTF_MOTIONCOR_BFACTOR}
sed -i "s@XXX_GTF_MOTIONCOR_BFACTOR_XXX@${GTF_MOTIONCOR_BFACTOR}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_BINNING_XXX -> ${GTF_MOTIONCOR_BINNING}
sed -i "s@XXX_GTF_MOTIONCOR_BINNING_XXX@${GTF_MOTIONCOR_BINNING}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_DEFECTFILE_XXX -> ${GTF_MOTIONCOR_DEFECTFILE}
sed -i "s@XXX_GTF_MOTIONCOR_DEFECTFILE_XXX@${GTF_MOTIONCOR_DEFECTFILE}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_GAINFLIP_XXX -> ${GTF_MOTIONCOR_GAINFLIP}
sed -i "s@XXX_GTF_MOTIONCOR_GAINFLIP_XXX@${GTF_MOTIONCOR_GAINFLIP}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_MOTIONCOR_GAINROT_XXX -> ${GTF_MOTIONCOR_GAINROT}
sed -i "s@XXX_GTF_MOTIONCOR_GAINROT_XXX@${GTF_MOTIONCOR_GAINROT}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}

# XXX_GTF_AMPL_CONTRAST_XXX -> ${GTF_AMPL_CONTRAST}
sed -i "s@XXX_GTF_AMPL_CONTRAST_XXX@${GTF_AMPL_CONTRAST}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_BOXSIZE_XXX -> ${GTF_CTFFIND_BOXSIZE}
sed -i "s@XXX_GTF_CTFFIND_BOXSIZE_XXX@${GTF_CTFFIND_BOXSIZE}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_ASTIGMATISM_XXX -> ${GTF_CTFFIND_ASTIGMATISM}
sed -i "s@XXX_GTF_CTFFIND_ASTIGMATISM_XXX@${GTF_CTFFIND_ASTIGMATISM}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_MAXRES_XXX -> ${GTF_CTFFIND_MAXRES}
sed -i "s@XXX_GTF_CTFFIND_MAXRES_XXX@${GTF_CTFFIND_MAXRES}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_MINRES_XXX -> ${GTF_CTFFIND_MINRES}
sed -i "s@XXX_GTF_CTFFIND_MINRES_XXX@${GTF_CTFFIND_MINRES}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_DEFOCUS_STEP_XXX -> ${GTF_CTFFIND_DEFOCUS_STEP}
sed -i "s@XXX_GTF_CTFFIND_DEFOCUS_STEP_XXX@${GTF_CTFFIND_DEFOCUS_STEP}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_DO_IGNORE_SEARCH_PARAMS_XXX -> ${GTF_CTFFIND_DO_IGNORE_SEARCH_PARAMS}
sed -i "s@XXX_GTF_CTFFIND_DO_IGNORE_SEARCH_PARAMS_XXX@${GTF_CTFFIND_DO_IGNORE_SEARCH_PARAMS}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_DO_EPA_XXX -> ${GTF_CTFFIND_DO_EPA}
sed -i "s@XXX_GTF_CTFFIND_DO_EPA_XXX@${GTF_CTFFIND_DO_EPA}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_GCTF_EXE_XXX -> ${GTF_GCTF_EXE}
sed -i "s@XXX_GTF_GCTF_EXE_XXX@${GTF_GCTF_EXE}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_GCTF_GPU_XXX -> ${GTF_GCTF_GPU}
sed -i "s@XXX_GTF_GCTF_GPU_XXX@${GTF_GCTF_GPU}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_USE_CTFFIND_INSTEAD_XXX -> ${GTF_USE_CTFFIND_INSTEAD}
sed -i "s@XXX_GTF_USE_CTFFIND_INSTEAD_XXX@${GTF_USE_CTFFIND_INSTEAD}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND4_EXE_XXX -> ${GTF_CTFFIND4_EXE}
sed -i "s@XXX_GTF_CTFFIND4_EXE_XXX@${GTF_CTFFIND4_EXE}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
# XXX_GTF_CTFFIND_MPI_XXX -> ${GTF_CTFFIND_MPI}
sed -i "s@XXX_GTF_CTFFIND_MPI_XXX@${GTF_CTFFIND_MPI}@g" ./${GTF_RELION_IT_OPTIONS_FILE_NAME}

echo "GoToFly(JK): Displaying contensts of relion_it_options.sh..."
echo "GoToFly(JK): ++++++++++++++++++++++++++++++"
cat ./${GTF_RELION_IT_OPTIONS_FILE_NAME}
echo "GoToFly(JK): ++++++++++++++++++++++++++++++"
echo "GoToFly(JK): "
echo "GoToFly(JK): Done"

if [[ ${GTF_DEBUG_MODE} != 0 ]]; then echo "GoToFly(JK): [GTF_DEBUG] "; fi
if [[ ${GTF_DEBUG_MODE} != 0 ]]; then echo "GoToFly(JK): [GTF_DEBUG] --------------------------------------------------"; fi
if [[ ${GTF_DEBUG_MODE} != 0 ]]; then echo "GoToFly(JK): [GTF_DEBUG] Good-bye gtf_create_relion_it_options.sh!"; fi
if [[ ${GTF_DEBUG_MODE} != 0 ]]; then echo "GoToFly(JK): [GTF_DEBUG] --------------------------------------------------"; fi
