#!/bin/sh

# GoToFly(JK) system environment variables
export GTF_SYSTEM_CRYOEM_SITE_NAME="KEK"
export GTF_SYSTEM_USER_ID="ikeda-em"

export GTF_SYSTEM_SRC_DOMAIN="cryoem-filetransfer.kek.jp"
export GTF_SYSTEM_SRC_ROOT_DIR_FPATH="/media/test/falcon3"
export GTF_SYSTEM_SRC_SESSION_DIR_NAME="XXX_GTF_SRC_SESSION_DIR_NAME_XXXX"
export GTF_SYSTEM_SRC_SESSION_DATA_DIR_RPATH_PATTEN="Images-Disc1/*/Data"
export GTF_SYSTEM_SRC_MIC_FILE_NAME_PATTERN="*_Fractions.mrc"
export GTF_SYSTEM_SRC_PATH_PATTERN="${GTF_SYSTEM_SRC_ROOT_DIR_FPATH}/${GTF_SYSTEM_SRC_SESSION_DIR_NAME}/${GTF_SYSTEM_SRC_SESSION_DATA_DIR_RPATH_PATTEN}/${GTF_SYSTEM_SRC_MIC_FILE_NAME_PATTERN}"

export GTF_SYSTEM_RSYNC_SRC="${GTF_SYSTEM_USER_ID}@${GTF_SYSTEM_SRC_DOMAIN}:${GTF_SYSTEM_SRC_PATH_PATTERN}"

export GTF_SYSTEM_DST_ROOT_DIR_FPATH="/gpfs/data/EM"
export GTF_SYSTEM_DST_MIC_DIR_RPATH="XXX_GTF_DST_MIC_DIR_RPATH_XXXX"
export GTF_SYSTEM_DST_MIC_FILE_NAME_PATTERN="${GTF_SYSTEM_SRC_MIC_FILE_NAME_PATTERN}"

export GTF_SYSTEM_RSYNC_DST="${GTF_SYSTEM_DST_ROOT_DIR_FPATH}/${GTF_SYSTEM_USER_ID}/${GTF_SYSTEM_DST_MIC_DIR_RPATH}"

export GTF_SYSTEM_DST_ORDERS_DEPOSIT_DIR_FPATH="${GTF_SYSTEM_DST_ROOT_DIR}/${GTF_SYSTEM_USER_ID}/mrk_rsync_test"

export GTF_SYSTEM_STATUS_CHECK_INTERVAL=120 # in seconds
export GTF_SYSTEM_STATUS_DISPLAY_INTERVAL=100 # number of micrograph movies
export GTF_SYSTEM_TIME_OUT_NO_UPDATE=600 # in seconds 10 min * 60 sec = 600
export GTF_SYSTEM_TIME_OUT_MAX=43200 # in seconds 12 hours * 60 min * 60 sec = 43200
